---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# test-release-process
name: 'ðŸ“„ Generate Pull Request'
description: 'Generates a pull request'

inputs:
  token:
    description: 'Github token with the required permissions'
    type: 'string'
    required: true

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: 'Write the date to a file ðŸ“†'
      shell: bash
      run: |
        # Write the date to a file ðŸ“†
        date=$(date +"%Y %B %d %R %Z")
        echo "date=$date" >> $GITHUB_ENV
        echo "Writing date to file: $date > date.txt" >> "$GITHUB_STEP_SUMMARY"
        echo "Writing date to file: $date > date.txt"
        echo "$date" > date.txt

    - name: 'Detect change ðŸ”'
      id: detect
      shell: bash
      run: |
        # Detect repository changes
        if [[ `git status --porcelain` ]]; then
          echo "changes=true" >> "$GITHUB_OUTPUT"
          echo '# Generating Pull Request' >> "$GITHUB_STEP_SUMMARY"
          echo 'Generating Pull Request'
          echo 'Changes made to repository âœ…' >> "$GITHUB_STEP_SUMMARY"
          echo 'Changes made to repository âœ…'
        else
          echo "changes=true" >> "$GITHUB_OUTPUT"
          echo 'No changes made to repository ðŸ’¬'
        fi

    - name: 'Raise Pull Request â¬‡ï¸'
      if: steps.detect.outputs.changes == 'true'
      # yamllint disable rule:line-length
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ env.date }}
        signoff: 'true'
        sign-commits: 'true'
        branch: automated-pr
        delete-branch: true
        title: ${{ env.date }}
        body: |
          ## Pull Request/Update Summary
          ${{ env.date }} > date.txt

          *Auto-generated by [lfreleng-actions/test-release-process][1]*

          [1]: https://github.com/lfreleng-actions/test-release-process

        labels: |
          automated pr
        draft: false
