---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a tag push event
name: "Generate Pull Request ⬇️"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "40 6 * * 0"

permissions: {}

jobs:
  generate-pr:
    name: 'Generate Pull Request ⬇️'
    runs-on: "ubuntu-24.04"
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "List pull requests with label/search"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # List pull requests with label/search
          requests=$(gh pr list -l 'automated pr')
          if [ -n "$requests" ]; then
            echo "Pull requests 💬"
            echo "$requests"
          fi

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
